### ISSUE TITLE
High level stokes coordinates can not be converted to pixel coordinates

### ISSUE THREAD

**Issue by Cadair** [DKISTDC/dkist#170]
To reproduce the error do: `ds.crop([..., 'I'])`

The fundamental issue here is that the [`StokesProfile`](https://github.com/spacetelescope/gwcs/blob/master/gwcs/coordinate_frames.py#L704) class in gWCS isn't sufficient to handle the requirements of being an APE 14 high level object. I have opened https://github.com/astropy/astropy/issues/13790 to track adding a more fully featured stokes coordinate object.

```[tasklist]
### Tasks
- [ ] https://github.com/astropy/astropy/pull/14482
- [ ] https://github.com/spacetelescope/gwcs/pull/452
- [ ] Changes to dkist-inventory to modify the table to run from 1 not 0.
```

**Comment by Cadair** [comment]
See https://github.com/astropy/astropy/pull/14482 for a WIP fix.

**Comment by SolarDrew** [comment]
> Changes to dkist-inventory to modify the table to run from 1 not 0.

By this do you mean the lookup table in the transform for the Stokes axis? Or some other table?
